### ISSUE TITLE
timing doesn't work properly

### ISSUE THREAD

**Issue by AdrickTench** [trueagi-io/metta-wam#128]
The following demonstrates `time!` fails to time `sleep!` accurately, and likewise `max-time!` fails to abort `sleep!`
```
metta+>!(time! (sleep! 1))
[
; eval_args([sleep!,1]) took 0.000298 secs. (298.50 microseconds)

True]
metta+>!(catch! (max-time! 1 (sleep! 2)) time_limit_exceeded time_limit_exceeded)
[True]
```

**Comment by TeamSPoon** [comment]
!(,(get-time!) (sleep! 1) (get-time!))
[(, 1726774806.2906268 True 1726774807.2910154)]

I see get-time!  is wall time and  time! is using cputime.. good find

we need a   (time! )  and a  without a bang `!` (time $Eval)  and (cpu-time $Eval)

**Comment by TeamSPoon** [comment]
```
metta+>!(catch! (max-time! 1 (sleep! 2)) time_limit_exceeded time_limit_exceeded)
[time_limit_exceeded]
```
