### ISSUE TITLE
max-time! only returns first result

### ISSUE THREAD

**Issue by AdrickTench** [trueagi-io/metta-wam#129]
`max-time!` only returns the first result but should return all (assuming it completes with the time limit). For example 
```
metta+>!(max-time! 1 (superpose (a b c)))
[a]
```
should return `[a, b, c]`

**Comment by AdrickTench** [comment]
Interesting to consider how we should handle getting some results before timing out. Do we throw time_limit_exceeded and discard results? Or can we somehow throw without losing the incremental results?

**Comment by TeamSPoon** [comment]
secretly my intent was to give results up until the time.. but good questions they want more thna to be cut off they want to know they got cut off

**Comment by TeamSPoon** [comment]
```
metta+>!(max-time! 1 (superpose (a b c)))
[a

, b

, c]
```
