### ISSUE TITLE
improve print behavior

### ISSUE THREAD

**Issue by AdrickTench** [trueagi-io/metta-wam#151]
In rust interpreter:
```
!(println! good)

[STDOUT] good
[()]
```
In mettalog:
```
[
good
()]
```
separating with `[STDOUT] good` rather than making the print appear to be a result is cleaner, let's make mettalog behave like rust here.

**Comment by TeamSPoon** [comment]
fixed now i think!

**Comment by TeamSPoon** [comment]
Can you confirm?

**Comment by AdrickTench** [comment]
Confirmed fixed.
