### ISSUE TITLE
Parse expression does not get reduced when used inside cons-atom

### ISSUE THREAD

**Issue by vulecoff** [trueagi-io/metta-wam#159]
**Bugged code**: `!(cons-atom (parse "1") ())`
- Expected: `[(1)]`
- Actual: `[ ( (parse "1") )]`

I suspected there're some edge cases in order of evaluation when combining these 2 specific expressions. `parse` works as expected when used with other expressions, so far:  
- `!(foldl-atom ((parse "1") 1 1) 0 $acc $x (+ $acc $x))` --> `3`
- `!(let $x (parse "1") (cons-atom $x ()))` --> `(1)`

**Comment by TeamSPoon** [comment]
fixed in  https://github.com/trueagi-io/metta-wam/commit/370696c064f1218172314cc78a71e3cbdd731c0f

metta+>!(cons-atom (parse "1") ())
[(1)]
metta+>!(foldl-atom ((parse "1") 1 1) 0 $acc $x (+ $acc $x))
[3]
metta+>!(let $x (parse "1") (cons-atom $x ()))
[(1)]
metta+>
