### ISSUE TITLE
Inconsistent order of evaluation for car-atom

### ISSUE THREAD

**Issue by vulecoff** [trueagi-io/metta-wam#163]
`(car-atom (+ 1 2))` --> `[]` (should return `[+]`), whereas `(car-atom (cons-atom 1 (2)))` --> `[cons-atom]`. It looks like for some reason arithmetic operations are eagerly evaluated, or maybe it's just that type-checking are not fully implemented in general.

**Comment by TeamSPoon** [comment]
MeTTa Should evalated `Expression`s ?

**Comment by TeamSPoon** [comment]
https://github.com/trueagi-io/metta-wam/commit/370696c064f1218172314cc78a71e3cbdd731c0f
