### ISSUE TITLE
space creation not working

### ISSUE THREAD

**Issue by AdrickTench** [trueagi-io/metta-wam#192]
The following works in Hyperon:
```
!(bind! &new-space (new-space))
!(add-atom &new-space (likes John Jane))
!(match &new-space (likes $x $y) ($x $y))
```
returning 
```
[()]
[()]
[(John Jane)]
```
In mettalog instead the returns are
```
[()]
[()]
[]
```

**Comment by AdrickTench** [comment]
Confirmed fixed.

**Comment by AdrickTench** [comment]
The tests in `output_load_tests.metta` rely on this working properly. Of course, they also depend on output + load functions working properly, so I could create some different tests dedicated to this specifically, if you think it's worth it?

**Comment by TeamSPoon** [comment]
Yes

**Comment by AdrickTench** [comment]
Some basic tests provided here https://github.com/AdrickTench/metta-testsuite/commit/0ff26c3b0b356d56f7640c2b3c872407b48e6a99
