### ISSUE TITLE
Interpreter stops working after expression that involves $_

### ISSUE THREAD

**Issue by vulecoff** [trueagi-io/metta-wam#208]
There seems to be an issue involving parsing variable `$_` in the recent Mettalog commits. Interpreter silently stops working right after expression that has `$_`, no errors or outputs. 

**Example**
```
!(SIGNPOST 1)
(foo $_)
!(SIGNPOST 2)
```
only gives `[(SIGNPOST 1)]`

**Comment by TeamSPoon** [comment]
This bug was breaking soooo much !


OK,. Supposedly fixed with 64cb365e22ca98399c996609190f5f142e4d74a8
Can you, @vulecoff, confirm if this is now fixed?  (If so close hte issue.. if not assign me)

**Comment by vulecoff** [comment]
It took me almost half a day to narrow down the bug... It seems to be working now. Mostly likely it's fully resolved given the fix. But I'll leave it open for a couple days or two to test larger scripts and see if any other weirdness comes up.
