### ISSUE TITLE
MeTTaLog mishandles missing closing parenthesis

### ISSUE THREAD

**Issue by ngeiswei** [trueagi-io/metta-wam#214]
## What is your problem?

MeTTaLog seems to enter infinite error message printing upon parsing a metta file with a missing closing parenthesis.

## How to reproduce your problem?

Run the following MeTTa code with MeTTaLog

```
(A B ; <- missing closing parenthesis
!(+ 40 2)
```

## What should it normally output?

A nice and clear message explaining that a closing parenthesis is missing.

## What do you get instead?

A seemingly infinite trace of errors starting with

```
mettalog bug.metta
% 23,906 inferences, 0.004 CPU in 0.004 seconds (100% CPU, 6629631 Lips)

#(ugtrace #(error #(stream_error #( : 1 #( : 1 1 ) ) #(syntax_error unexpected_end_of_file "Unexpected end of file in list"))) $10000)

%~ FIlE: /home/nilg/Work/SingularityNET/ai-dsl/experimental/ai-service-composition/english-to-chinese-song/bug.metta:3 
(0)$[system] system:'$c_call_prolog'.  no(clause). 
...
```

## What else do you have to say?

Tested on metta-wam revision 352b2973f

**Comment by TeamSPoon** [comment]
Hi @ngeiswei, 

I think i fixed this.. though it prints a warning now 

![image](https://github.com/user-attachments/assets/9b002f63-c5a3-4c55-84fb-d77ea1a87c11)

**Comment by TeamSPoon** [comment]
@ngeiswei,  If you are satified with this (that is that you get the warning now) feel free to close this bug or suggest what would make things better

**Comment by ngeiswei** [comment]
That's perfect, thank you.
