### ISSUE TITLE
Differences in Mettalog behaviour between OSs and console or graphical environments.

### ISSUE THREAD

**Issue by stassa** [trueagi-io/metta-wam#227]
Mettalog behaves differently depending on whether it's started on windows or linux (incl. WSL) and whether it's started with or without a graphical environment (i.e. the SWI-Prolog IDE).

Known differences so-far are listed below.

## Starting Mettalog from the OS shell

On Linux/WSL the following shell commands start mettalog in a Prolog shell or the Mettalog repl, respectively:

```
stassaP@VARYS:/mnt/c/Users/me/Documents/Prolog/metta/metta-wam-wsl$ 
swipl $PWD/prolog/metta_lang/metta_interp.pl --prolog
1 ?- repl.

metta+>

stassaP@VARYS:/mnt/c/Users/me/Documents/Prolog/metta/metta-wam-wsl$
swipl $PWD/prolog/metta_lang/metta_interp.pl --repl

metta+>
```

On Windows, in a console environment the same commands exit without starting the mettalog repl. 

On Windows, both commands first output a large amount of text, dumping the entire `&corelib` file, as reported below. I omit the console output to avoid extreme cluttering of this issue but see the file `starting_on_windows.log` included in the next section.

## Starting Mettalog from a SWI-Prolog shell

On Windows, in a terminal console (powershell), mettalog can be loaded by consulting `prolog/metta_lang/metta_interp.pl` as follows: 

```
stassaP@VARYS> C:\Users\me\Documents\Prolog\metta\metta-wam_win
> swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 9.3.10-21-g9712e8e0f)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

1 ?- [prolog/metta_lang/metta_interp].

```

However, this immediately prints the entire contents of the mettalog `&corelib` to the console, before dropping to the SWI Prolog shell. See the following file with a comprehensive dump of such a session:

[starting_on_windows.log](https://github.com/user-attachments/files/18213052/starting_on_windows.log)

On Linux, loading mettalog in the same way does not dump the `&corelib` to the console::

```
stassaP@VARYS:/mnt/c/Users/me/Documents/Prolog/metta/metta-wam-wsl$ swipl
Welcome to SWI-Prolog (threaded, 64 bits, version 9.3.8-27-g80f956be2)
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software.
Please run ?- license. for legal details.

For online help and background, visit https://www.swi-prolog.org
For built-in help, use ?- help(Topic). or ?- apropos(Word).

?- [prolog/metta_lang/metta_interp].
true.

2 ?- repl.

metta+>
```

## Starting Mettalog in the SWI-Prolog IDE

On Windows, in the SWI-Prolog IDE, consulting `prolog/metta_lang/metta_interp.pl` raises an error. The repl can then be started but remains unresponsive:

```
?- [prolog/metta_lang/metta_interp].
;           #(set_debug transpiler false)
;           #(set_debug overtime 4.0)
;           #(set_debug overflow 1000)
;           #(set_debug eval false)
;           #(set_debug load silent)
;           #(set_debug trace-on-load false)
;           #(set_debug exec false)
;           #(set_debug error non-type)
;           #(set_debug fail false)
;           #(set_debug test true)
;           #(set_debug test false)
;           #(set_debug fail false)
; libswipl: [C:\Program Files\swipl\bin\swipl-win.exe,C:\Users\me\Documents\Prolog\metta\metta-wam_win\load_ide.pl]
ERROR: Assertion failed: user:metta_atom('&corelib',[:,'Any','Type'])
  [38] prolog_stack:backtrace(10) at c:/program files/swipl/library/prolog_stack.pl:494
  [37] prolog_debug:assertion_failed(fail,user:metta_atom('&corelib',[:,'Any','Type'])) at c:/program files/swipl/library/debug.pl:391
  [36] prolog_debug:assertion(user:metta_atom('&corelib',[:,'Any','Type'])) at c:/program files/swipl/library/debug.pl:379
  [35] load_corelib_file at c:/users/yegoblynqueenne/documents/prolog/metta/metta-wam_win/prolog/metta_lang/metta_loader.pl:3687
  [34] really_use_corelib_file at c:/users/yegoblynqueenne/documents/prolog/metta/metta-wam_win/prolog/metta_lang/metta_loader.pl:3629
  [33] use_corelib_file at c:/users/yegoblynqueenne/documents/prolog/metta/metta-wam_win/prolog/metta_lang/metta_loader.pl:3618
  [32] '$run_init_goal'('<garbage_collected>') at c:/program files/swipl/boot/init.pl:826
  [31] catch(system:'$run_init_goal'(user:use_corelib_file),_903106,system:'$initialization_error'(_903174,user:use_corelib_file,'c:/users/yegoblynqueenne/documents/prolog/metta/metta-wam_win/prolog/metta_lang/metta_interp.pl':2286)) at c:/program files/swipl/boot/init.pl:565
  [30] catch_with_backtrace('<garbage_collected>','<garbage_collected>','<garbage_collected>') at c:/program files/swipl/boot/init.pl:645
  [29] '$run_init_goal'(user:use_corelib_file,'c:/users/yegoblynqueenne/documents/prolog/metta/metta-wam_win/prolog/metta_lang/metta_interp.pl':2286) at c:/program files/swipl/boot/init.pl:815
   Call: (37) [prolog_debug] prolog_debug:assertion_failed ? leap
;                 #( --> #( ==> #( , #( / #(metta_atom_asserted $10000 (==> $10001 $10002)) #(nonvar $10000) ) #(metta_atom_asserted $10003 $10001) ) #(metta_atom_asserted $10003 $10002) ) #( :- #(pfcAdd #( ==> #( , #( / #(metta_atom_asserted $10000 (==> $10001 $10002)) #(nonvar $10000) ) #(metta_atom_asserted $10003 $10001) ) #(metta_atom_asserted $10003 $10002) )) ) )
;                 #( --> #( ==> a b ) #( :- #(pfcAdd #( ==> a b )) ) )
;                 #( --> #( ==> b bb ) #( :- #(pfcAdd #( ==> b bb )) ) )
;                 #( --> a #( :- #(pfcAdd a) ) )
true.

[debug] 2 ?- repl.

metta+>!(print abcd)
metta+>
true.
```

If the SWI-Prolog IDE is invoked on the command line it prints an error and exits immediately; there is no time to read the error (but we can assume it's the same as above):

```
> swipl-win $PWD/prolog/metta_lang/metta_interp.pl --prolog
stassaP@VARYS> C:\Users\me\Documents\Prolog\metta\metta-wam_win

> swipl-win $PWD/prolog/metta_lang/metta_interp.pl --repl
stassaP@VARYS> C:\Users\me\Documents\Prolog\metta\metta-wam_win
```
 
The error above is a failed-assertion error raised because the mettalog `&corelib` is not loaded. This is similar, but not identical to issue #223 

On Linux, starting the IDE causes the repl to hang, as reported in Isssue #217 that this issue seems to be connected, but not identical to.

## Using the Mettalog repl

On Windows, once started in a prolog shell, the mettalog repl accepts commands but then stops printing the prompt afterwards:

```
3 ?- repl.
metta+>!(print abcd)
abcd

Deterministic: abcd

[abcd]
!(print edfg)
edfg

Deterministic: edfg

[edfg]
```

Note also that the above output is lightly colourised:

![image](https://github.com/user-attachments/assets/9a9fc195-ecfd-4205-bcab-0dbeaaf05a82)

On Linux the repl prints the prompt again after every executed expression and is not colourised:

```
2 ?- repl.

metta+>!(print arg;oiajr)
'arg;oiajr'

Deterministic: arg;oiajr

[arg;oiajr]

metta+>
```
![image](https://github.com/user-attachments/assets/e7aacffe-8a78-469c-b54b-2cc7474a79e1)

**Comment by stassa** [comment]
Also see:
metta+> Imperative Commands Not Working with swipl-win https://github.com/trueagi-io/metta-wam/issues/217

**Comment by stassa** [comment]
Also also see:

Error on loading stdlib_metta and corelib in a fresh Docker container https://github.com/trueagi-io/metta-wam/issues/223

This reports the same assertion error as seen when starting the SWI-Prolog IDE on windows. #223 was probably caused a bad path for `afn_stem_filename/2` in `prolog/metta_lang/corelib.metta.buffer~`. Each OS writes those paths in its own style and trying to load the buffer~ file with a path in the other OS's style causes some mixup that manifests as the assertion error.

The ultimate reason for the error is that the mettalog `&corelib` fails to load. There seems to be multiple ways this can happen and they all have to do with the way the mettalog environment is setup on different platforms (OSs and terminal or graphical environments).

**Comment by TeamSPoon** [comment]
A big differences is 

`is_compatio` is  false on windows 
and `is_mettalog` is true  on windows 
(but not set to `true` in linux)

`is_mettalog` has far reaching consequences since it allows mettalog to have more diverse types of output not allowed on in hyperon.   Such as colored text.

on linux this is equivalent to supplying `--log`.

what i am going to suggest is to comment oyut these three lines of `metta_interp.ppl`

Line 274 `is_mettalog:- is_win64,!.`
Line 292 `is_compatio0:- is_win64,!,fail.`
Line 301 `keep_output:- is_win64,!.`

This way you have the same codepaths between windows and linux..

**Comment by stassa** [comment]
Fixed by recent commits.
