### ISSUE TITLE
up arrow not retrieving last input in repl

### ISSUE THREAD

**Issue by jazzbox35** [trueagi-io/metta-wam#228]
If I enter the wrong number of parenthesis in mettalog I do get an error message, however I have to type the entire input back in because the up arrow doesn't retrieve the bad input for easy correction.

**Comment by stassa** [comment]
I can't reproduce this, e.g. 

```
% Starting on WSL with: swipl $PWD/prolog/metta_lang/metta_interp.pl --repl

metta+>!(print abcd))
abcd
[abcd]

metta+>!((print abcd
| ))
abcd
[(abcd)]

metta+>
```

Can you copy/paste an example session where this happens?

**Comment by jazzbox35** [comment]
I can't recreate this either now. In fact if I input 

!(+ 1 2)))))))))))))))

It ignores the superfluous parens. I cannot recreate the problem either so I assume program modified or my installation was the problem. I will close for now and reopen if I see it again. 

Thanks
