### ISSUE TITLE
Review and Document Metta Functions Across Source Files

### ISSUE THREAD

**Issue by TeamSPoon** [trueagi-io/metta-wam#71]
This task involves reviewing and documenting all functions defined in various Metta source files, and organizing this information into a comprehensive spreadsheet. This will ensure that all functions are properly documented, tested, and implemented across different parts of the codebase.

### Task

1. **Glean Functions from Source Files:**
   - Review the following Metta source files to identify all defined functions:
     - `metta_eval`
     - `src/canary/stdlib_mettalog.metta` This couble an awesome source!
     - `hyperon-expermental/**/stdlib*.*`
     - `hyperon-expermental/**/stdlib*.py`
     - Relevant Rust code
   - Identify any missing functions across these files.

2. **Create a Metta Functions Spreadsheet:**
 **For now can be in Googledocs publically accessable**
   - Develop a spreadsheet to organize the identified functions.
   - The spreadsheet should include the following columns for each function:
     - **Function Name**: The name of the function.
     - **Documentation (@doc)**: Whether the function is documented.
     - **Test Creation**: Whether tests have been created for the function.
     - **Implementation in the Interpreter**: Whether the function is implemented in the Metta interpreter.
     - **Implementation in the Transpiler**: Whether the function is implemented in the Metta transpiler.
     - **Declaration of Argument Types**: Whether the function's argument types are declared.

4. **Populate the Spreadsheet:**
   - For each function identified, fill in the details in the spreadsheet.
   - Mark the status of documentation, testing, interpreter implementation, transpiler implementation, and argument type declaration.

### Acceptance Criteria

- All functions from the specified source files are listed in the spreadsheet.
- The spreadsheet is fully populated with the status of documentation, testing, implementation, and argument types for each function.
- Any missing functions or discrepancies are noted for further action.

**Comment by royward** [comment]
I've got this mostly done (by hand, maybe a scripted version would be better), I've been through all the files except test.

https://docs.google.com/spreadsheets/d/1-ICkIlV1cCCDe8RVu1Y6is3q72wAu2g51aiCaNjS8d8/edit?gid=0#gid=0
