### ISSUE TITLE
Figure Out How to Get Allure Test Reports to Publish to GitHub Pages in `ci.yml`

### ISSUE THREAD

**Issue by TeamSPoon** [trueagi-io/metta-wam#80]
The current CI pipeline generates Allure test reports, but they need to be automatically published to GitHub Pages. This task involves updating the [`ci.yml`](https://github.com/trueagi-io/metta-wam/blob/main/.github/workflows/ci.yml) workflow to generate and publish Allure reports to GitHub Pages, allowing for easy access and viewing of test results.

### Task

1. **Update the [`ci.yml`](https://github.com/trueagi-io/metta-wam/blob/main/.github/workflows/ci.yml) Workflow:**
   - Modify the existing [`ci.yml`](https://github.com/trueagi-io/metta-wam/blob/main/.github/workflows/ci.yml) to include steps that will publish the generated Allure test reports to GitHub Pages.
   - Ensure that the reports are generated and stored in a format that is suitable for publishing.

2. **Generate and Store Allure Reports:**
   - Configure the workflow to generate the Allure reports in the `./allure-report` directory.
   - Ensure that the `allure-report` directory is ready for deployment to GitHub Pages.

3. **Set Up GitHub Pages Deployment:**
   - Add steps to the workflow that will push the contents of the `allure-report` directory to the `gh-pages` branch.
   - Ensure that the GitHub Pages site is correctly configured to serve the Allure reports.

4. **Test the Deployment Process:**
   - Run the workflow and verify that the Allure reports are correctly published to GitHub Pages.
   - Check the generated pages to ensure they display the test reports as expected.

5. **Document the Setup:**
   - Provide clear documentation on how the Allure reports are generated and published to GitHub Pages.
   - Include troubleshooting tips for any common issues that might arise.

### Acceptance Criteria

- The CI pipeline successfully publishes the Allure reports to GitHub Pages.
- The generated Allure reports are accessible and correctly displayed via the GitHub Pages site.
- Documentation is provided detailing the setup and any potential issues.

**Comment by AdrickTench** [comment]
1-4 complete as of https://github.com/trueagi-io/metta-wam/pull/83

Where do you want docs for 5? An explanation on this issue, comments in the .yml, a readme in the workflow directory?
Not sure I know enough atm to really provide up-front help with troubleshooting but I can at least outline the process.

**Comment by AdrickTench** [comment]
OK, no nothing written other than what's in the commit message, which doesn't seem like it merits a wiki page.
